name: Update RSS Feeds

on:
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run `make ci`
        env:
          NF_SIGNATURE_KEY: ${{ secrets.NF_SIGNATURE_KEY }}
        run: make ci

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email 'action@github.com'
          git config --global user.name 'Github Action'
          git checkout --orphan gh-pages
          git reset
          cp rss_data.json index.json
          git add index.json
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
