name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./NewsFlowFrontend
        run: npm install

      - name: Run tests
        working-directory: ./NewsFlowFrontend
        run: npm test

      - name: Build project
        working-directory: ./NewsFlowFrontend
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: svelte-app
          path: ./NewsFlowFrontend/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: svelte-app
          path: dist/

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
          rsync -av --delete dist/ gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy frontend"
          git push
